title: libreim

# theme: minima
baseurl: ""
assets_path: /assets

locale: "es"
permalink: pretty

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock


# Tag configuration
tag_dir: "/t"
tag_title_prefix: ""
tag_title_suffix: ""

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
